#!/usr/bin/env bash
# KOINO Capital — Client Acquisition: Prospect Research Tool
# Usage: ./prospect.sh "Company Name" ["industry"]
# Requires: ollama running with qwen2.5:3b (or set OLLAMA_MODEL)

set -euo pipefail

COMPANY="${1:?Usage: prospect.sh \"Company Name\" [\"industry\"]}"
INDUSTRY="${2:-unknown}"
MODEL="${OLLAMA_MODEL:-qwen2.5:3b}"
OLLAMA_URL="${OLLAMA_URL:-http://localhost:11434}"
OUTPUT_DIR="${PROSPECT_DIR:-/tmp/prospects}"

mkdir -p "$OUTPUT_DIR"

TIMESTAMP=$(date +%Y%m%d-%H%M%S)
OUTFILE="$OUTPUT_DIR/$(echo "$COMPANY" | tr ' ' '-' | tr '[:upper:]' '[:lower:]')-$TIMESTAMP.md"

echo "====================================="
echo "  PROSPECT RESEARCH: $COMPANY"
echo "====================================="
echo ""

# Check ollama is running
if ! curl -sf "$OLLAMA_URL/api/tags" > /dev/null 2>&1; then
    echo "ERROR: Ollama not running at $OLLAMA_URL"
    echo "Start it with: ollama serve"
    exit 1
fi

# Build the research prompt
PROMPT="You are a B2B sales research analyst. Research and create a prospect brief for the company: $COMPANY (industry: $INDUSTRY).

Generate a structured prospect brief with these sections:

## Company Overview
- What they do (1-2 sentences)
- Estimated size (employees, revenue range)
- Business model
- Key products/services

## Pain Signal Analysis
Based on what companies like this typically struggle with:
- Top 3 likely pain points
- What would trigger them to seek outside help
- What they've probably already tried

## Personalization Hooks
Generate 3 specific hooks for outreach:
1. A likely recent company event or trend to reference
2. A specific business challenge to reference
3. A value-add insight you could share

## Decision Maker Map
- Who likely makes buying decisions for services (title, role)
- Who influences the decision
- Who could block the deal

## ICP Fit Score (0-100)
Score this prospect on:
- Budget likelihood (0-25): Can they afford services?
- Need urgency (0-25): How badly do they need help?
- Accessibility (0-25): How easy to reach decision-makers?
- Fit quality (0-25): How well do they match a typical ICP?

Total: __/100

## Recommended Outreach
- Best channel (email, LinkedIn, phone, referral)
- Best time to reach out
- Draft opening line (1 sentence)

Be specific and actionable. No generic advice."

# Call ollama
echo "Researching $COMPANY via $MODEL..."
echo ""

RESPONSE=$(curl -sf "$OLLAMA_URL/api/generate" \
    -d "$(jq -n --arg model "$MODEL" --arg prompt "$PROMPT" \
        '{model: $model, prompt: $prompt, stream: false}')" \
    | jq -r '.response // "ERROR: No response from model"')

# Format output
{
    echo "# Prospect Brief: $COMPANY"
    echo "**Generated:** $(date '+%Y-%m-%d %H:%M')"
    echo "**Industry:** $INDUSTRY"
    echo "**Model:** $MODEL"
    echo ""
    echo "---"
    echo ""
    echo "$RESPONSE"
    echo ""
    echo "---"
    echo "*Generated by KOINO Capital client-acquisition skill*"
} | tee "$OUTFILE"

echo ""
echo "====================================="
echo "Saved to: $OUTFILE"
echo "====================================="
