#!/bin/bash
set -euo pipefail

# Clawd Provisioner — Automated Clawd Bot Setup
# Supports: macOS (Intel/Apple Silicon), Ubuntu, Debian, Raspberry Pi OS
# Run with: sudo bash provision.sh [--headless] [--node-id NAME]

# Configuration
NODE_ID="${NODE_ID:-clawd-$(hostname)-$(date +%s)}"
OPENCLAW_DIR="${OPENCLAW_DIR:-/opt/clawd}"
OPENCLAW_REPO="https://github.com/openclaw/openclaw.git"
LOG_FILE="/var/log/clawd-provision.log"
REPORT_FILE="/tmp/clawd-provision-report.json"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Logging
exec > >(tee -a "$LOG_FILE") 2>&1

log() { echo -e "${GREEN}[$(date +'%Y-%m-%d %H:%M:%S')] $*${NC}"; }
warn() { echo -e "${YELLOW}[$(date +'%Y-%m-%d %H:%M:%S')] WARNING: $*${NC}"; }
error() { echo -e "${RED}[$(date +'%Y-%m-%d %H:%M:%S')] ERROR: $*${NC}" >&2; }

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   error "This script must be run as root (use sudo)"
   exit 1
fi

log "Starting Clawd Provisioner — Node ID: $NODE_ID"

# Detect OS
OS="$(uname -s)"
case "$OS" in
    Darwin)
        PLATFORM="macos"
        PKG_MGR="brew"
        ;;
    Linux)
        PLATFORM="linux"
        if command -v apt-get &>/dev/null; then
            PKG_MGR="apt"
        elif command -v yum &>/dev/null; then
            PKG_MGR="yum"
        else
            error "Unsupported Linux package manager"
            exit 1
        fi
        ;;
    *)
        error "Unsupported OS: $OS"
        exit 1
        ;;
esac

log "Detected platform: $PLATFORM, package manager: $PKG_MGR"

# Update system
case "$PKG_MGR" in
    brew)
        brew update
        brew upgrade || true
        ;;
    apt)
        apt-get update
        apt-get upgrade -y
        ;;
    yum)
        yum update -y
        ;;
esac

# Install dependencies
log "Installing dependencies..."
case "$PKG_MGR" in
    brew)
        brew install node git curl wget jq tmux
        ;;
    apt)
        apt-get install -y nodejs npm git curl wget jq tmux
        ;;
    yum)
        yum install -y nodejs npm git curl wget jq tmux
        ;;
esac

# Verify Node.js version (need >= 18)
NODE_VERSION="$(node -v 2>/dev/null || echo 'v0')"
REQUIRED_VERSION="v18"
if [[ "$(printf '%s\n' "$REQUIRED_VERSION" "$NODE_VERSION" | sort -V | head -n1)" != "$REQUIRED_VERSION" ]]; then
    warn "Node.js version $NODE_VERSION is below recommended $REQUIRED_VERSION. Attempting to upgrade..."
    case "$PKG_MGR" in
        brew) brew upgrade node ;;
        apt) apt-get install -y nodejs npm ;;
        yum) yum install -y nodejs npm ;;
    esac
fi

# Create clawd user if not exists
if ! id -u clawd &>/dev/null; then
    log "Creating system user 'clawd'"
    useradd -r -s /bin/bash -m -d /home/clawd clawd
fi

# Prepare directories
mkdir -p "$OPENCLAW_DIR"
chown clawd:clawd "$OPENCLAW_DIR"

# Clone OpenClaw if not present
if [[ ! -d "$OPENCLAW_DIR/.git" ]]; then
    log "Cloning OpenClaw repository..."
    sudo -u clawd git clone "$OPENCLAW_REPO" "$OPENCLAW_DIR"
fi

# Install OpenClaw dependencies
log "Installing OpenClaw dependencies (this may take a few minutes)..."
cd "$OPENCLAW_DIR"
sudo -u clawd npm ci --production

# Create environment file
ENV_FILE="$OPENCLAW_DIR/.env"
if [[ ! -f "$ENV_FILE" ]]; then
    log "Creating environment configuration"
    cat > "$ENV_FILE" <<EOF
# Generated by Clawd Provisioner
NODE_ID=$NODE_ID
OPENCLAW_HOME=$OPENCLAW_DIR
# Add your API keys below after running 'openclaw gateway start'
# MATON_API_KEY=your_key_here
EOF
    chown clawd:clawd "$ENV_FILE"
    chmod 600 "$ENV_FILE"
fi

# Set up systemd service (Linux) or launchd (macOS)
case "$PLATFORM" in
    linux)
        SERVICE_FILE="/etc/systemd/system/clawd.service"
        if [[ ! -f "$SERVICE_FILE" ]]; then
            log "Creating systemd service"
            cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=Clawd Bot
After=network.target

[Service]
Type=simple
User=clawd
WorkingDirectory=$OPENCLAW_DIR
EnvironmentFile=$ENV_FILE
ExecStart=$OPENCLAW_DIR/node_modules/.bin/openclaw daemon start
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF
            systemctl daemon-reload
            systemctl enable clawd
        fi
        systemctl start clawd
        SERVICE_STATUS=$(systemctl is-active clawd)
        ;;
    macos)
        LAUNCHD_PLIST="$HOME/Library/LaunchAgents/io.openclaw.clawd.plist"
        mkdir -p "$HOME/Library/LaunchAgents"
        if [[ ! -f "$LAUNCHD_PLIST" ]]; then
            log "Creating launchd service"
            cat > "$LAUNCHD_PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>io.openclaw.clawd</string>
    <key>WorkingDirectory</key>
    <string>$OPENCLAW_DIR</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>NODE_ID</key>
        <string>$NODE_ID</string>
        <key>OPENCLAW_HOME</key>
        <string>$OPENCLAW_DIR</string>
    </dict>
    <key>ProgramArguments</key>
    <array>
        <string>$OPENCLAW_DIR/node_modules/.bin/openclaw</string>
        <string>daemon</string>
        <string>start</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
</dict>
</plist>
EOF
        fi
        launchctl load "$LAUNCHD_PLIST" 2>/dev/null || true
        launchctl start io.openclaw.clawd 2>/dev/null || true
        sleep 2
        if launchctl list | grep -q io.openclaw.clawd; then
            SERVICE_STATUS="active"
        else
            SERVICE_STATUS="failed"
        fi
        ;;
esac

# Validation checks
log "Running validation checks..."
CHECKS=(
    "Node.js installed: node -v"
    "npm available: npm -v"
    "Git available: git --version"
    "OpenClaw CLI: $OPENCLAW_DIR/node_modules/.bin/openclaw --version"
    "Service running: systemctl is-active clawd || launchctl list | grep -q io.openclaw.clawd"
)

RESULTS=()
for check in "${CHECKS[@]}"; do
    cmd="${check#*: }"
    desc="${check%%:*}"
    if eval "$cmd" &>/dev/null; then
        RESULTS+=("{\"check\":\"$desc\",\"status\":\"ok\"}")
        log "✓ $desc"
    else
        RESULTS+=("{\"check\":\"$desc\",\"status\":\"failed\"}")
        error "✗ $desc"
    fi
done

# Generate JSON report
cat > "$REPORT_FILE" <<EOF
{
  "provisioner": "clawd-provisioner v1.0",
  "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "node_id": "$NODE_ID",
  "platform": "$PLATFORM",
  "openclaw_dir": "$OPENCLAW_DIR",
  "service_status": "$SERVICE_STATUS",
  "checks": [
    $(IFS=,; echo "${RESULTS[*]}")
  ],
  "next_steps": [
    "Review the environment file: $ENV_FILE",
    "Add your MATON_API_KEY to the .env file",
    "Run: openclaw gateway status to verify connectivity",
    "Test: openclaw sessions_spawn --runtime subagent --task 'hello'"
  ]
}
EOF

log "Provisioning complete. Report: $REPORT_FILE"
log "Service status: $SERVICE_STATUS"
log "Next: Set MATON_API_KEY in $ENV_FILE, then run 'openclaw gateway status'"

# Final summary
echo ""
echo "========================================="
echo "  Clawd Provisioner — Summary"
echo "========================================="
echo "Node ID:     $NODE_ID"
echo "Platform:    $PLATFORM"
echo "Install dir: $OPENCLAW_DIR"
echo "Service:     $SERVICE_STATUS"
echo "Report:      $REPORT_FILE"
echo "========================================="

exit 0
